### ISSUE TITLE
Drupal console write location

### ISSUE THREAD

**Issue by johnmoney** [mortenson/drupal-docker-lite#13]
Hi Sam! I was playing with ddl and drupal console last night

`ddl drupal generate:module --module="Foo" --module-name="foo" --module-path="/modules/custom"`

The files were written out to /var/www/html/modules/custom/foo but I can't figure out how to access that. They were not in the mount /code.

**Comment by mortenson** [comment]
Hi @johnmoney - sorry about the late response.

When you run `ddl drupal`, that is actually running Drupal Console from inside the container, not on your host system. As a result, the current directory is `/var/www/html`, which is why files were output relative to that directory. You can confirm the current directory by running `ddl exec pwd`.

Here's a weird thing - I'm using a recent Drupal Console and core version, and when I run `ddl drupal generate:module --module="Foo" --machine-name="foo" --module-path="/modules/custom"`  it puts the module where I would expect - in `/var/www/html/docroot/docroot/modules/custom/`. Maybe something has changed since you first looked at this?
